name: iKuuu Checkin

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  ACCOUNTS: ${{ secrets.ACCOUNTS }}

jobs:
  checkin:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run checkin
        run: python playwright_checkin.py
